services:
  postgres:
    image: postgres
    container_name: spPostgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - spotiData:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: spRedis
    restart: always
    ports:
      - "6379:6379"

  pgweb:
    image: sosedoff/pgweb
    container_name: spPgweb
    restart: always
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: "postgres://postgres:postgres@spPostgres:5432/postgres?sslmode=disable"
    ports:
      - "8081:8081"
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: spClickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouseData:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: spMeilisearch
    ports: ["7700:7700"]
    environment:
      # - MEILI_MASTER_KEY=your-master-key-optional
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
  #   container_name: spElastic
  #   restart: always
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   volumes:
  #     - elasticData:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

volumes:
  spotiData:
  clickhouseData:
  meili_data:
