syntax = "proto3";

package playlist.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/Chimder/spoti/proto/gen/playlist";

service PlaylistService {
  rpc CreatePlaylist(CreatePlaylistRequest) returns (CreatePlaylistResponse);
  rpc GetPlaylistById(GetPlaylistByIdRequest) returns (GetPlaylistByIdResponse);
  rpc AddToPlaylist(AddToPlaylistRequest) returns (AddToPlaylistResponse);
  rpc UpdatePlaylist(UpdatePlaylistRequest) returns (UpdatePlaylistResponse);
  rpc DeleteFromPlaylist(DeleteFromPlaylistRequest) returns (DeleteFromPlaylistResponse);
  rpc GetAllUserPlaylists(GetAllUserPlaylistsRequest) returns (GetAllUserPlaylistsResponse);
}
message Playlist {
  string id = 1;
  string owner_id = 2;
  string name = 3;
  string description = 4;
  int32 disc_number = 5;
  string image = 6;
  bool is_public = 7;
  uint32 total = 8;
  google.protobuf.Timestamp created_at = 9;
}
message PlaylistJson {
  Playlist playlist = 1;
  PlaylistTracks tracks = 2;
}

message CreatePlaylistRequest {
  string owner_id = 1;
  string playlist_name = 2;
  string description = 3;
  string image = 4;
  bool is_public = 5;
}
message CreatePlaylistResponse {
  string id = 1;
}

message GetPlaylistByIdRequest {
  string playlist_id = 1;
}
message GetPlaylistByIdResponse {
  PlaylistJson playlist = 1;
}

message AddToPlaylistRequest {
  string playlist_id = 1;
  string track_id = 2;
}
message AddToPlaylistResponse {}

message UpdatePlaylistRequest {
  string playlist_id = 1;
  optional string name = 2;
  optional string description = 3;
  optional bool is_public = 4;
}
message UpdatePlaylistResponse {}

message DeleteFromPlaylistRequest {
  string playlist_id = 1;
  string track_id = 2;
}
message DeleteFromPlaylistResponse {}

message GetAllUserPlaylistsRequest {
  string user_id = 1;
}
message GetAllUserPlaylistsResponse {
  Playlist playlist = 1;
}

message PlaylistTracks {
  uint32 total = 1;
  int32 limit = 2;
  int32 offset = 3;
  repeated PlaylistTrack items = 4;
}

message PlaylistTrack {
  google.protobuf.Timestamp added_at = 1;
  bool is_local = 2;
  Track track = 3;
}

message Track {
  string id = 1;
  string name = 2;
  int32 track_number = 3;
  int32 disc_number = 4;
  bool explicit = 5;
  repeated Artist artists = 6;
}

message Artist {
  string id = 1;
  string name = 2;
  string uri = 3;
}
